

pipeline {
    agent {
        docker {
            image 'node:10.16-alpine' 
            args '-p 3000:3000' 
        }
    }
    git 'https://github.com/nagabhushanamn/airbus-automation'
    stages {
        stage('build') { 
            dir("Txr-system-UI") {
                steps {
                    sh 'npm install' 
                }
            }
        }
    }
    
}