

pipeline {
    agent any
    stages {
        stage('install dependencies') { 
            steps {
                dir('Txr-system-UI') {
                    sh 'npm install' 
                }
            }
        }
        stage('test') { 
            steps {
                dir('Txr-system-UI') {
                    
                }
            }
        }
        stage('build') { 
            steps {
                dir('Txr-system-UI') {
                    sh 'npm run build' 
                }
            }
        }
        stage('Building image') {
            steps{
                script {
                docker.build registry + ":$BUILD_NUMBER"
                }
            }
        }
    }
}