
node {

    stage 'checkout'
    
    git 'https://github.com/nagabhushanamn/airbus-automation'
    
    dir('Txr-system') {
    
        stage("compile and analysis") {
        
    	    parallel 'Compilation': {
                sh "./mvnw clean install -DskipTests"
            }, 
            'Static Analysis': {
                stage("Checkstyle") {
                    sh "./mvnw checkstyle:checkstyle"
                    step([$class: 'CheckStylePublisher',
                      canRunOnFailed: true,
                      defaultEncoding: '',
                      healthy: '100',
                      pattern: '**/target/checkstyle-result.xml',
                      unHealthy: '90',
                      useStableBuildAsReference: true
                    ])
                }    
    	    }
        }
        
        stage("tests") {
            parallel 'Unit tests': {
                stage("unit tests") {
                    try {
                        sh "./mvnw test -Punit"
                    } catch(err) {
                        step([$class: 'JUnitResultArchiver', testResults: 
                          '**/target/surefire-reports/TEST-*.xml'])
                        throw err
                    }
                   step([$class: 'JUnitResultArchiver', testResults: 
                     '**/target/surefire-reports/TEST-*.xml'])
                }
            }, 'Integration tests': {
                stage("integration tests") {
                    try {
                        sh "./mvnw test -Pintegration"
                    } catch(err) {
                        step([$class: 'JUnitResultArchiver', testResults: 
                          '**/target/surefire-reports/TEST-*.xml'])
                        throw err
                    }
                    step([$class: 'JUnitResultArchiver', testResults: 
                      '**/target/surefire-reports/TEST-*.xml'])
                }
            }
        }
        
        stage("staging") {
                sh 'pid=\$(lsof -i:8181 -t); [ -z "\$pid" ] && echo "Empty" || kill -TERM \$pid'
                withEnv(['JENKINS_NODE_COOKIE=dontkill']) {
                    sh 'nohup ./mvnw spring-boot:run -Dserver.port=8181 &'
                }   
        }    
    }
}     